build:
  stage: build
  script:
    - apt-get update -qy
    - apt -y update
    - apt -y install apt-utils
    - apt -y install python3.8 python3-pip
    - apt -y upgrade



RunningUnitTests:
  stage: test
  script:
    - pip install pytest
    - python3 Test*.py


