build:
  stage: build
  script:
    - apt-get update -qy
    - apt-get -qy update
    - apt-get -y install python3-pip



RunningUnitTests:
  stage: test
  script:
    - pip install pytest
    - python3 Test*.py


